### ISSUE TITLE
Extraction of an incorrect path

### ISSUE THREAD

**Issue by espdev** [InsightSoftwareConsortium/ITKMinimalPathExtraction#22]
Hello!
Thanks for this project contributing to ITK!

I try to use this module for paths extraction from angiographic images. But the algorithm works incorrectly sometimes.

For example:
<img width="300" alt="1" src="https://cloud.githubusercontent.com/assets/1299189/15798583/7746cb56-2a45-11e6-825b-1084c6d54f4d.png">

<img width="300" alt="2" src="https://cloud.githubusercontent.com/assets/1299189/15798584/7aaae30e-2a45-11e6-8f37-18873bcaa208.png">

Also this error occurs even at the test data. For example, `Noise-01-Speed.mhd`

My test speed image and start/end points:
[test_image.zip](https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/files/298749/test_image.zip)

I use python wrappings and `GradientDescentOptimizer`:

``` python
import itk

def mpe(speed_image, start_point, end_point, way_points=None):
    # ITK Types
    Point = itk.Point.F2
    CostFunction = itk.SingleImageCostFunction.IF2
    Interpolator = itk.LinearInterpolateImageFunction.IF2D
    PathInformation = itk.SpeedFunctionPathInformation.PD2
    MinimalPathExtractor = itk.SpeedFunctionToPathFilter.IF2PPP2

    interpolator = Interpolator.New()

    cost_function = CostFunction.New()
    cost_function.SetInterpolator(interpolator)

    optimizer = itk.GradientDescentOptimizer.New()
    optimizer.SetNumberOfIterations(1000)

    path_info = PathInformation.New()
    path_info.SetStartPoint(Point(start_point))
    path_info.SetEndPoint(Point(end_point))

    if way_points:
        for p in way_points:
            path_info.AddWayPoint(Point(p))

    path_extractor = MinimalPathExtractor.New()
    path_extractor.SetInput(speed_image)
    path_extractor.SetCostFunction(cost_function)
    path_extractor.SetOptimizer(optimizer)
    path_extractor.SetTerminationValue(1.0)
    path_extractor.AddPathInformation(path_info)

    path_extractor.Update()

    path = path_extractor.GetOutput(0)
    vertices_list = path.GetVertexList()

    if vertices_list.Size() == 0:
        raise ValueError('Path has not been found')

    px = []
    py = []

    for i in range(vertices_list.Size()):
        vertex = vertices_list.ElementAt(i)
        px.append(vertex[0])
        py.append(vertex[1])

    return px, py
```

**Comment by romangrothausmann** [comment]
This might be the result due to `SetTerminationValue(1.0)`, see
https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/blob/f658f822646ac6b2755b23ab99b58c8b38eeda68/include/itkArrivalFunctionToPathFilter.h#L120-L125
or https://itk.org/Doxygen/html/classitk_1_1ArrivalFunctionToPathFilter.html
