### ISSUE TITLE
documentation/comment missing in itkIterateNeighborhoodOptimizer

### ISSUE THREAD

**Issue by romangrothausmann** [InsightSoftwareConsortium/ITKMinimalPathExtraction#57]
Going through the code, I am wondering why `i` goes up to 2 here (not FullyConnected):
https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/blob/f658f822646ac6b2755b23ab99b58c8b38eeda68/src/itkIterateNeighborhoodOptimizer.cxx#L137
in contrast to just 1 here (FullyConnected):
https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/blob/f658f822646ac6b2755b23ab99b58c8b38eeda68/src/itkIterateNeighborhoodOptimizer.cxx#L161
If that is correct, it might be worth a comment in the code, since a reason for that irregularity is non-obvious.

**Comment by romangrothausmann** [comment]
I think I found the reason for `i+=2` in one case and  `i+=1` in the other:
FullyConnected also needs edge cases which only get reached with `i==0`. 
Not FullyConnected does not check these and the case `i==0` would be an unnecessary extra computation for the center position. This center position case is part of the FullyConnected computation but does not get regarded as a valid solution.

**Comment by dzenanz** [comment]
This looked self-answered. If code/comment change is desired, please make a PR.
