### ISSUE TITLE
Python wrapping itk - SpeedFunctionToPathFilter returns zero points of centerline

### ISSUE THREAD

**Issue by Franek18** [InsightSoftwareConsortium/ITKMinimalPathExtraction#79]
Hi everyone,
first of all I would like to thank you for this module, it seems to work great for given example:
https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/blob/master/examples/DigitalSubtractionAngiographyVesselPath.ipynb

Unfortunately when I tried it on my data which are: **.png** file of vessels and **.mdh** and **.zraw** files generated from a DICOM the program from the example returns **0** points as an extracted centerline without any error.
**GetVertexList()** returns **0** instead of **ie. 2200**.
I changed nothing in it except of files and Points on a path.
My utils are:
- Python 3.6.9
- ITK 5.1.0

I'm wondering if problem could be in my speed image (.mdh, .zraw) or because my image file is **itkImageRGBUC2** instead of **itkImageUC2** from the example.

I will be thankful for some advices about it.

Regards
Franek

**Comment by thewtex** [comment]
Hi Franek,

Yes, the speed image should be a scalar image. It can be cast when reading with:

```
speed = itk.imread('speedfile.mhd', itk.F)
```

**Comment by Franek18** [comment]
Thanks for replay Matt,
I implement your tip but it still doesn't work :(.

**Comment by Franek18** [comment]
Sorry Matt, probably I misled you.
My image file - .png file is **itkImageRGBUC2** instead of **itkImageUC2** and I am wondering whether this can be a problem for centerline extraction?

**Comment by thewtex** [comment]
@Franek18, yes, the intensity, by reading as `itk.UC` or `itk.F` should be used for the speed.

**Comment by aylward** [comment]
I am marking as closed.  If the issue remains after using itk.F or itk.UC when reading the speed image, please re-open.
