### ISSUE TITLE
Slow instantiation of SpeedFunctionPathInformation

### ISSUE THREAD

**Issue by FluencyLiu** [InsightSoftwareConsortium/ITKMinimalPathExtraction#82]
Hi, 
I tested the python example code on my laptop and found the instantiation of SpeedFunctionPathInformation is very slow.

It takes about 7s to run the following line with Core i7-10510U and 8GB RAM.
`PathInformationType = itk.SpeedFunctionPathInformation[PointType]`

Is there some time-consuming operation during the instantiation? Is there any way to speed it up in python?

Thx.

**Comment by thewtex** [comment]
Hi @FluencyLiu ,

A new version was released. Does it still take 7s for that operation?

**Comment by FluencyLiu** [comment]
> Hi @FluencyLiu ,
> 
> A new version was released. Does it still take 7s for that operation?

I solved it by wrapping the ITKMinimalPathExtraction with pybind11 directly. In my implementation, itk.SpeedFunctionPathInformation[PointType] will not appear in python. The program speeded a lot.

I'll test your new release soon. Thx.

**Comment by Zhehao-Hu** [comment]
Hi @FluencyLiu ,
Would you mind sharing your speed-up implementation with pybind11 wrapping? Thanks!
